### ISSUE TITLE
Form crear nuevo usuario (admin)

### ISSUE THREAD

**Issue by Nidev-lab** [MarianoGirbau/JuegaFulbo-Front#1]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario admin.
3. Quise registrar un nuevo usuario.

## Resultado esperado

• Que al registrar un nuevo usuario no se permitan numeros ni signos en los nombres de los usuarios.

## Resultado actual

• Se permiten colocar numeros y signos donde va el nombre.

## Captura

![image](https://github.com/MarianoGirbau/JuegaFulbo-Front/assets/53904695/46eaf9fd-5015-43a2-b823-21a8d4ea8a08)
![image](https://github.com/MarianoGirbau/JuegaFulbo-Front/assets/53904695/01e56bea-db14-4021-87fb-737198fab249)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Hola chicos buenas! Estuve revisando el proyecto y la verdad que esta muy bien logrado, no hay mucho que corregir o modificar, igualmente les dejo esto y seria todo chicos.

**Comment by Aron9377** [comment]
Buenos dias Nico , correcciones realizadas! Saludos !
